name: Module CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'release/**'
      - develop
      - 'feature/**'
  workflow_dispatch:
    inputs:
      comment:
        description: Just a simple comment to know the purpose of the manual build
        required: false

jobs:
  call:
    name: Default CI Flow
    uses: openimis/openimis-be_py/.github/workflows/ci_module.yml@sonar_update

