name: Module CI
on:
  pull_request:
  push:
    - devlop
    - main
  workflow_dispatch:
    inputs:
      comment:
        description: Just a simple comment to know the purpose of the manual build
        required: false
jobs:
  call:
    uses: openimis/openimis-be_py/.github/workflows/ci_module.yml@sonar_update

